package com.Gathering_be.global.enums;

public enum TechStack {
    ANGULAR("Angular"),
    AWS("AWS"),
    AZURE("Azure"),
    C("C"),
    CLOUDFLARE("Cloudflare"),
    CPP("C++"),
    CS("C#"),
    CSS("CSS"),
    DART("Dart"),
    DJANGO("Django"),
    DOCKER("Docker"),
    EMOTION("Emotion"),
    EXPRESSJS("Express.js"),
    FASTAPI("FastAPI"),
    FIGMA("Figma"),
    FIREBASE("Firebase"),
    FLASK("Flask"),
    FLUTTER("Flutter"),
    FORTRAN("Fortran"),
    GCP("GCP"),
    GIT("Git"),
    GRAPHQL("GraphQL"),
    HTML("HTML"),
    ILLUSTRATOR("Illustrator"),
    JAVA("Java"),
    JAVASCRIPT("JavaScript"),
    KOTLIN("Kotlin"),
    KUBERNETES("Kubernetes"),
    LARAVEL("Laravel"),
    MATLAB("MATLAB"),
    MONGODB("MongoDB"),
    MYSQL("MySQL"),
    NESTJS("Nest.js"),
    NEXTJS("Next.js"),
    NODEJS("Node.js"),
    NUXTJS("Nuxt.js"),
    PHOTOSHOP("Photoshop"),
    PHP("PHP"),
    POSTGRESQL("PostgreSQL"),
    POSTMAN("Postman"),
    PREMIERE("Premiere"),
    PYTHON("Python"),
    R("R"),
    REACT("React"),
    RUST("Rust"),
    SASS("Sass"),
    SPRING("Spring"),
    SQLITE("SQLite"),
    SUPABASE("Supabase"),
    SVELTE("Svelte"),
    SWIFT("Swift"),
    TAILWINDCSS("Tailwind CSS"),
    TYPESCRIPT("TypeScript"),
    UNITY("Unity"),
    UNREALENGINE("Unreal Engine"),
    VERCEL("Vercel"),
    VITE("Vite"),
    VUE("Vue"),
    ;

    private final String description;

    TechStack(String description) {
        this.description = description;
    }
}
