export interface TechStack {
  id: string;
  title: string;
}

export const techStacks: TechStack[] = [
  { id: 'JAVASCRIPT', title: 'JavaScript' },
  { id: 'TYPESCRIPT', title: 'TypeScript' },
  { id: 'REACT', title: 'React' },
  { id: 'VUE', title: 'Vue.js' },
  { id: 'NEXTJS', title: 'Next.js' },
  { id: 'NUXTJS', title: 'Nuxt.js' },
  { id: 'ANGULAR', title: 'Angular' },
  { id: 'SVELTE', title: 'Svelte' },
  { id: 'NODEJS', title: 'Node.js' },
  { id: 'NESTJS', title: 'NestJS' },
  { id: 'JAVA', title: 'Java' },
  { id: 'KOTLIN', title: 'Kotlin' },
  { id: 'SPRING', title: 'Spring' },
  { id: 'PYTHON', title: 'Python' },
  { id: 'DJANGO', title: 'Django' },
  { id: 'FASTAPI', title: 'FastAPI' },
  { id: 'FLASK', title: 'Flask' },
  { id: 'PHP', title: 'PHP' },
  { id: 'LARAVEL', title: 'Laravel' },
  { id: 'C', title: 'C' },
  { id: 'CPP', title: 'C++' },
  { id: 'CS', title: 'C#' },
  { id: 'R', title: 'R' },
  { id: 'SWIFT', title: 'Swift' },
  { id: 'FLUTTER', title: 'Flutter' },
  { id: 'UNITY', title: 'Unity' },
  { id: 'UNREALENGINE', title: 'Unreal Engine' },
  { id: 'MYSQL', title: 'MySQL' },
  { id: 'POSTGRESQL', title: 'PostgreSQL' },
  { id: 'MONGODB', title: 'MongoDB' },
  { id: 'SQLITE', title: 'SQLite' },
  { id: 'FIREBASE', title: 'Firebase' },
  { id: 'SUPABASE', title: 'Supabase' },
  { id: 'AWS', title: 'AWS' },
  { id: 'GCP', title: 'Google Cloud' },
  { id: 'AZURE', title: 'Azure' },
  { id: 'DOCKER', title: 'Docker' },
  { id: 'KUBERNETES', title: 'Kubernetes' },
  { id: 'FIGMA', title: 'Figma' },
  { id: 'PHOTOSHOP', title: 'Photoshop' },
  { id: 'ILLUSTRATOR', title: 'Illustrator' },
  { id: 'PREMIERE', title: 'Premiere Pro' },
  { id: 'CLOUDFLARE', title: 'Cloudflare' },
  { id: 'CSS', title: 'CSS' },
  { id: 'DART', title: 'Dart' },
  { id: 'EMOTION', title: 'Emotion' },
  { id: 'EXPRESSJS', title: 'ExpressJS' },
  { id: 'FORTRAN', title: 'Fortran' },
  { id: 'GIT', title: 'Git' },
  { id: 'GRAPHQL', title: 'GraphQL' },
  { id: 'HTML', title: 'HTML' },
  { id: 'MATLAB', title: 'Matlab' },
  { id: 'POSTMAN', title: 'Postman' },
  { id: 'RUST', title: 'Rust' },
  { id: 'SASS', title: 'Sass' },
  { id: 'TAILWINDCSS', title: 'TailwindCSS' },
  { id: 'VERCEL', title: 'Vercel' },
  { id: 'VITE', title: 'Vite' }
];
